[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Function calling with constrained decoding for small LLMs."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "llm-sdk",
    "numpy",
    "pydantic>=2",
]

[tool.uv.sources]
llm-sdk = { path = "llm_sdk" }

[dependency-groups]
dev = [
    "flake8",
    "mypy",
]
